function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintIndices{MathOptInterface.VectorOfVariables}})   # time: 0.16566403
    Base.precompile(Tuple{typeof(operate_output_index!),typeof(+),Core.Type{T},Int64,MathOptInterface.VectorAffineFunction{T},MathOptInterface.ScalarAffineFunction{T}})   # time: 0.15875036
    Base.precompile(Tuple{typeof(operate_output_index!),typeof(+),Core.Type{T},Int64,MathOptInterface.VectorQuadraticFunction{T},MathOptInterface.ScalarAffineFunction{T}})   # time: 0.15633158
    isdefined(MathOptInterface.Utilities, Symbol("#129#131")) && Base.precompile(Tuple{getfield(MathOptInterface.Utilities, Symbol("#129#131")),Tuple{Type, Type}})   # time: 0.11132371
    Base.precompile(Tuple{typeof(haskey),IndexMap,MathOptInterface.ConstraintIndex})   # time: 0.10403696
    isdefined(MathOptInterface.Utilities, Symbol("#169#170")) && Base.precompile(Tuple{getfield(MathOptInterface.Utilities, Symbol("#169#170")),ModelScalarConstraints{Float64, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.ZeroOne}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.Integer}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.EqualTo{Float64}}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.GreaterThan{Float64}}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.LessThan{Float64}}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.Interval{Float64}}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.Semicontinuous{Float64}}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.Semiinteger{Float64}}}})   # time: 0.09272527
    Base.precompile(Tuple{typeof(MathOptInterface.get),ModelScalarConstraints{Float64, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.ZeroOne}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.Integer}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.EqualTo{Float64}}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.GreaterThan{Float64}}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.LessThan{Float64}}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.Interval{Float64}}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.Semicontinuous{Float64}}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.Semiinteger{Float64}}},MathOptInterface.ListOfConstraintTypesPresent})   # time: 0.06413026
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.AbstractConstraintAttribute,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.EqualTo{Float64}}})   # time: 0.06362042
    Base.precompile(Tuple{typeof(setindex!),IndexMap,MathOptInterface.ConstraintIndex{MathOptInterface.VectorOfVariables, S},MathOptInterface.ConstraintIndex{MathOptInterface.VectorOfVariables, S}})   # time: 0.044760488
    Base.precompile(Tuple{typeof(eachscalar),MathOptInterface.AbstractVectorFunction})   # time: 0.02726099
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintAttributesSet})   # time: 0.025037823
    Base.precompile(Tuple{typeof(operate),typeof(-),Core.Type{T},MathOptInterface.VariableIndex,MathOptInterface.VariableIndex})   # time: 0.013867571
    Base.precompile(Tuple{typeof(MathOptInterface.set),UniversalFallback{Model{Float64}},MathOptInterface.ObjectiveFunction{MathOptInterface.ScalarAffineFunction{Float64}},MathOptInterface.ScalarAffineFunction{Float64}})   # time: 0.012700463
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ObjectiveFunction{MathOptInterface.ScalarAffineFunction{Float64}}})   # time: 0.011575397
    Base.precompile(Tuple{typeof(operate),typeof(-),Core.Type{T},MathOptInterface.ScalarAffineFunction{T},MathOptInterface.VariableIndex})   # time: 0.011173957
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ConstraintFunction,MathOptInterface.ConstraintIndex{MathOptInterface.VariableIndex}})   # time: 0.009778816
    Base.precompile(Tuple{typeof(operate),typeof(-),Core.Type{T},MathOptInterface.VariableIndex,MathOptInterface.VariableIndex})   # time: 0.008548293
    Base.precompile(Tuple{typeof(operate_output_index!),typeof(+),Core.Type{T<:(MathOptInterface.ScalarAffineFunction)},Int64,MathOptInterface.VectorAffineFunction{T<:(MathOptInterface.ScalarAffineFunction)},T<:(MathOptInterface.ScalarAffineFunction)})   # time: 0.008367826
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.AbstractVariableAttribute,MathOptInterface.VariableIndex})   # time: 0.00778668
    Base.precompile(Tuple{typeof(normalize_constant),Union{MathOptInterface.ScalarAffineFunction{T}, MathOptInterface.ScalarQuadraticFunction{T}},MathOptInterface.AbstractScalarSet})   # time: 0.007373223
    Base.precompile(Tuple{typeof(map_indices),IndexMap,MathOptInterface.AbstractVariableAttribute,Any})   # time: 0.003764275
    Base.precompile(Tuple{typeof(operate_output_index!),typeof(+),Core.Type{T<:(MathOptInterface.ScalarAffineFunction)},Int64,MathOptInterface.VectorQuadraticFunction{T<:(MathOptInterface.ScalarAffineFunction)},T<:(MathOptInterface.ScalarAffineFunction)})   # time: 0.003584574
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ConstraintSet,MathOptInterface.ConstraintIndex{MathOptInterface.VariableIndex, S}})   # time: 0.003001473
    Base.precompile(Tuple{Core.kwftype(typeof(normalize_constant)),NamedTuple{(:allow_modify_function,), Tuple{Bool}},typeof(normalize_constant),Union{MathOptInterface.ScalarAffineFunction{T}, MathOptInterface.ScalarQuadraticFunction{T}},MathOptInterface.AbstractScalarSet})   # time: 0.002658625
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ConstraintFunction,MathOptInterface.ConstraintIndex})   # time: 0.0025297
    Base.precompile(Tuple{Core.kwftype(typeof(normalize_constant)),NamedTuple{(:allow_modify_function,), Tuple{Bool}},typeof(normalize_constant),MathOptInterface.ScalarAffineFunction,MathOptInterface.AbstractScalarSet})   # time: 0.002248451
    Base.precompile(Tuple{typeof(operate),typeof(-),Core.Type{T},MathOptInterface.ScalarAffineFunction,MathOptInterface.VariableIndex})   # time: 0.001331793
    Base.precompile(Tuple{Core.kwftype(typeof(normalize_constant)),NamedTuple{(:allow_modify_function,), Tuple{Bool}},typeof(normalize_constant),MathOptInterface.AbstractScalarFunction,MathOptInterface.AbstractScalarSet})   # time: 0.001112703
    isdefined(MathOptInterface.Utilities, Symbol("#124#127")) && Base.precompile(Tuple{getfield(MathOptInterface.Utilities, Symbol("#124#127")),Tuple{DataType, DataType}})   # time: 0.001071846
end
