function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintIndices{MathOptInterface.VectorOfVariables}})   # time: 0.1024936
    Base.precompile(Tuple{typeof(haskey),IndexMap,MathOptInterface.ConstraintIndex})   # time: 0.10050886
    Base.precompile(Tuple{typeof(operate_output_index!),typeof(+),Core.Type{T},Int64,MathOptInterface.VectorAffineFunction{T},MathOptInterface.ScalarAffineFunction{T}})   # time: 0.09914507
    isdefined(MathOptInterface.Utilities, Symbol("#129#131")) && Base.precompile(Tuple{getfield(MathOptInterface.Utilities, Symbol("#129#131")),Tuple{Type, Type}})   # time: 0.07057574
    isdefined(MathOptInterface.Utilities, Symbol("#169#170")) && Base.precompile(Tuple{getfield(MathOptInterface.Utilities, Symbol("#169#170")),ModelScalarConstraints{Float64, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.ZeroOne}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.Integer}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.EqualTo{Float64}}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.GreaterThan{Float64}}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.LessThan{Float64}}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.Interval{Float64}}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.Semicontinuous{Float64}}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.Semiinteger{Float64}}}})   # time: 0.05956915
    Base.precompile(Tuple{typeof(MathOptInterface.get),ModelScalarConstraints{Float64, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.ZeroOne}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.Integer}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.EqualTo{Float64}}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.GreaterThan{Float64}}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.LessThan{Float64}}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.Interval{Float64}}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.Semicontinuous{Float64}}, VectorOfConstraints{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.Semiinteger{Float64}}},MathOptInterface.ListOfConstraintTypesPresent})   # time: 0.03998505
    Base.precompile(Tuple{typeof(operate_output_index!),typeof(+),Core.Type{T},Int64,MathOptInterface.VectorQuadraticFunction{T},MathOptInterface.ScalarAffineFunction{T}})   # time: 0.039188724
    Base.precompile(Tuple{typeof(setindex!),IndexMap,MathOptInterface.ConstraintIndex{MathOptInterface.VectorOfVariables, S},MathOptInterface.ConstraintIndex{MathOptInterface.VectorOfVariables, S}})   # time: 0.027770996
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ListOfConstraintAttributesSet})   # time: 0.015186915
    Base.precompile(Tuple{typeof(eachscalar),MathOptInterface.AbstractVectorFunction})   # time: 0.010417198
    Base.precompile(Tuple{typeof(operate),typeof(-),Core.Type{T},MathOptInterface.VariableIndex,MathOptInterface.VariableIndex})   # time: 0.008499016
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.AbstractConstraintAttribute,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.EqualTo{Float64}}})   # time: 0.008309954
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ObjectiveFunction{MathOptInterface.ScalarAffineFunction{Float64}}})   # time: 0.007840981
    Base.precompile(Tuple{typeof(MathOptInterface.set),UniversalFallback{Model{Float64}},MathOptInterface.ObjectiveFunction{MathOptInterface.ScalarAffineFunction{Float64}},MathOptInterface.ScalarAffineFunction{Float64}})   # time: 0.007440154
    Base.precompile(Tuple{typeof(operate),typeof(-),Core.Type{T},MathOptInterface.ScalarAffineFunction{T},MathOptInterface.VariableIndex})   # time: 0.007087668
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ConstraintFunction,MathOptInterface.ConstraintIndex{MathOptInterface.VariableIndex}})   # time: 0.006418028
    Base.precompile(Tuple{typeof(operate),typeof(-),Core.Type{T},MathOptInterface.VariableIndex,MathOptInterface.VariableIndex})   # time: 0.005743369
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.AbstractVariableAttribute,MathOptInterface.VariableIndex})   # time: 0.004692404
    Base.precompile(Tuple{typeof(normalize_constant),Union{MathOptInterface.ScalarAffineFunction{T}, MathOptInterface.ScalarQuadraticFunction{T}},MathOptInterface.AbstractScalarSet})   # time: 0.004679412
    Base.precompile(Tuple{typeof(operate_output_index!),typeof(+),Core.Type{T<:(MathOptInterface.ScalarAffineFunction)},Int64,MathOptInterface.VectorAffineFunction{T<:(MathOptInterface.ScalarAffineFunction)},T<:(MathOptInterface.ScalarAffineFunction)})   # time: 0.003715886
    Base.precompile(Tuple{typeof(map_indices),IndexMap,MathOptInterface.AbstractVariableAttribute,Any})   # time: 0.002337646
    Base.precompile(Tuple{Core.kwftype(typeof(normalize_constant)),NamedTuple{(:allow_modify_function,), Tuple{Bool}},typeof(normalize_constant),MathOptInterface.ScalarAffineFunction,MathOptInterface.AbstractScalarSet})   # time: 0.001900234
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ConstraintSet,MathOptInterface.ConstraintIndex{MathOptInterface.VariableIndex, S}})   # time: 0.00170712
    Base.precompile(Tuple{typeof(operate_output_index!),typeof(+),Core.Type{T<:(MathOptInterface.ScalarAffineFunction)},Int64,MathOptInterface.VectorQuadraticFunction{T<:(MathOptInterface.ScalarAffineFunction)},T<:(MathOptInterface.ScalarAffineFunction)})   # time: 0.001258044
    Base.precompile(Tuple{typeof(MathOptInterface.get),UniversalFallback{Model{Float64}},MathOptInterface.ConstraintFunction,MathOptInterface.ConstraintIndex})   # time: 0.001248268
    Base.precompile(Tuple{Core.kwftype(typeof(normalize_constant)),NamedTuple{(:allow_modify_function,), Tuple{Bool}},typeof(normalize_constant),Union{MathOptInterface.ScalarAffineFunction{T}, MathOptInterface.ScalarQuadraticFunction{T}},MathOptInterface.AbstractScalarSet})   # time: 0.001158871
end
